package com.usermanagement.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;

@Getter
@Setter
@ToString
@NoArgsConstructor
@Entity
@Table(name = "users", schema = "dbo")
@Schema(name = "User", description = "A user of the system")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    @Schema(description = "Unique identifier of the user, generated by the database. "
            + "Omit when creating a user; set it to the path id when updating one.",
            example = "1")
    private Long id;
    @Column(name = "first_name")
    @Schema(description = "First name of the user. Must be at least 3 characters when provided.",
            example = "John", minLength = 3)
    private String firstName;
    @Column(name = "last_name")
    @Schema(description = "Last name of the user", example = "Smith")
    private String lastName;
    @Column(name = "email", unique = true)
    @Schema(description = "Email address of the user. Must be unique.", example = "john@gmail.com")
    private String email;
    @Column(name = "address")
    @Schema(description = "Postal address of the user", example = "Thach That, Ha Noi")
    private String address;
    @Column(name = "image")
    @Schema(description = "URL or path of the user's avatar image", example = "https://example.com/avatars/john.png",
            nullable = true)
    private String image;

    @Enumerated(EnumType.STRING)
    @Schema(description = "Gender of the user", example = "MALE")
    private Gender gender;
}
